FROM antrea/ubuntu:24.04
ARG VERSION
ARG COMMIT_HASH
ARG BUILD_DATE

RUN apt-get update --fix-missing
RUN apt-get install -y ca-certificates

RUN mkdir -p /opt/scripts
COPY opt/cluster-manager /opt/cluster-manager
COPY entrypoint/cluster-manager.sh /opt/scripts/entrypoint.sh
RUN chmod +x /opt/scripts/entrypoint.sh
CMD ["bash", "-c", "/opt/scripts/entrypoint.sh"]
