FROM antrea/ubuntu:24.04
ARG VERSION
ARG COMMIT_HASH
ARG BUILD_DATE

RUN apt-get update --fix-missing
RUN apt-get install -y curl libgomp1 ca-certificates wget

RUN wget https://github.com/unum-cloud/USearch/releases/download/v2.26.0/usearch_linux_amd64_2.26.0.deb
RUN apt install -y ./usearch_linux_amd64_2.26.0.deb
RUN rm usearch_linux_amd64_2.26.0.deb

RUN mkdir -p /opt/scripts
COPY opt/faiss /opt/faiss
COPY opt/cluster /opt/cluster
COPY scripts/entrypoint/gateway.sh /opt/scripts/entrypoint.sh
COPY scripts/register-cluster.sh /opt/scripts/register-cluster.sh
RUN chmod +x /opt/scripts/entrypoint.sh
RUN chmod +x /opt/scripts/register-cluster.sh
RUN ln -s /opt/scripts/register-cluster.sh /usr/local/bin/register-cluster
RUN ln -s /opt/faiss/build/c_api/libfaiss_c.so /usr/lib/libfaiss_c.so
RUN ln -s /opt/faiss/build/faiss/libfaiss.so /usr/lib/libfaiss.so
CMD ["bash", "-c", "/opt/scripts/entrypoint.sh"]
